### PR TITLE
Add h3

### PR DESCRIPTION
**Pull request by crazycapivara**
Add h3, R bindings for H3, a hexagonal hierachical spatial indexing system

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks for the contribution!  Unfortunately, I'm reluctant to add packages that require libraries only available on individual GitHub repositories as it is difficult for us to ensure we will be able to provide consistent, long-term access to specific versions required for the build (i.e. we have no way of knowing if the GitHub repo will disappear).   Note that all packages currently included here install specifically from either the version-stable MRAN snapshots from CRAN or from Bioconductor repositories, making sure the image builds are reproducible; see https://github.com/rocker-org/rocker-versioned/blob/master/README.md

Users are of course welcome to extend these images using a separate Dockerfile, we just want to make sure the rocker images provide a dependable base.  If `h3` does go to CRAN we'd be happy to include it here; the H3 hexes looks super useful!  

Feedback from @Robinlovelace, @edzer and others on this always appreciated too.

**Comment by edzer** [comment]
I will be happy to look at it once it hits CRAN. There seems to be more than one github package interfacing to h3. Beyond their coolness, I'd be interested which practical problems h3, and these packages, solve for users of spatial data.

**Comment by Robinlovelace** [comment]
I also think being conservative is important. I've not used H3 and would be interested to learn more about how it can be used to solve common geographic problems before putting it in a docker container used by hundreds if not thousands of people. I think a big user base and/or peer review are important - the user base being the reason behind my minor contribution to rocker #6

**Comment by crazycapivara** [comment]
> I will be happy to look at it once it hits CRAN.

Yep, the goal is to put it on CRAN. In this case I am not pretty used to how to deal with external dependencies, when submitting a package to CRAN. @edzer : Is it enough to put a note to the H3 C library to the `SystemRequirements` in the `DESCRIPTION` file and the detailed installation requirements to the `README`? 

> There seems to be more than one github package interfacing to h3.

Yes, but most packages use `V8` and `h3-js` as I also first did with [h3forr](https://github.com/crazycapivara/h3forr). In this case it is no problem to build the package on windows and on the CRAN servers, but for the cost of performance. [h3r](https://github.com/scottmmjackson/h3r) seems to be somehow discontinued.

> Beyond their coolness, I'd be interested which practical problems h3, and these packages, solve for users of spatial data.

Amongs others it is pretty useful for suitability analysis to identify optimal locations, where you need to take different layers into account and want to create a composite layer. There is a good example [over here](https://observablehq.com/@nrabinowitz/h3-tutorial-suitability-analysis).

@Robinlovelace, @cboettig: I can understand that your are reluctant to add packages that require libraries only available on individual GitHub repositories. So, I hope it will make its way on CRAN.

**Comment by cboettig** [comment]
closing for now until h3 is on CRAN

**Pull request closed without merging**
