### PR TITLE
Address #6 (not tested)

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Testing it here: https://hub.docker.com/r/robinlovelace/geospatial/builds/bg7njyqqn6drbbpxieaxpgf/

**Comment by cboettig** [comment]
@Robinlovelace Can you try the version I just pushed here instead? https://github.com/rocker-org/geospatial/commit/8563dc795c5de5d018320cd9a7e5a9de5d5d7c60.  Installs `tmap` for me, though I haven't run anything in `tmap` on it.  

`libv8-dev` is already included upstream, so I've omitted it here.  Also, these libraries are already available from the debian repos, so I've just installed them from there.  I'm quite loath to add a ppa because it's much harder to know if it is stable and if it will play nicely with the existing repos, particularly once we backport this to the older version tags.  (For instance, on jessie-based images you can end up getting binaries built against newer versions of glibc etc, and end up needing two versions of glibc on the image and having incompatible binaries).  We also know the debian repos are going to stick around and be stable.  If for some reason the version of protobuf is too old on the debian repo, we can compile it on the container from source.  

Lemme know if the new commit does what you need and I can backport it to the tagged versions.

**Comment by Robinlovelace** [comment]
Awesome, cheers for that, will do.

**Comment by Robinlovelace** [comment]
Update: seems to have worked. [This](https://hub.docker.com/r/robinlovelace/geocompr/builds/) is the build status after changing the dockerfile to the following:

```
FROM rocker/geospatial
RUN R -e "remotes::install_github('robinlovelace/geocompr')"
```

**Comment by Robinlovelace** [comment]
One question: do you recommend putting docker build status icons in the repo? Grateful for any pointers on how to do that if so.

**Comment by cboettig** [comment]
Great, I've backported it to the recent versioned tags as well.

We use the Docker badges from http://shields.io/, just take a look at the README here and adjust the badge based on your repo name on Docker Hub.  They aren't crucial, but it's nice to see that builds are automated and building successfully.

**Pull request closed without merging**
