### PR TITLE
add spatialreg to devel branch

### LINKED ISSUE #23: spatialreg package support
Spatial regression models that used to be in spdep have been moved to a new package [spatialreg](https://cran.r-project.org/web/packages/spatialreg/index.html). Could this package be included in the geospatial library please?

### PR DESCRIPTION
**Pull request by dlebauer**
fixes #23 along w/ #34

### CODE REVIEW

**Comment by dlebauer** [comment]
failing with `unable to locate package liblwgeom-dev` ... sorry, that's beyond my capacity to track down! 
https://travis-ci.org/github/rocker-org/geospatial/builds/710199387#L229

**Comment by eddelbuettel** [comment]
See https://packages.ubuntu.com/search?keywords=liblwgeom-dev&searchon=names&suite=all&section=all

**Comment by dlebauer** [comment]
@eddelbuettel the library installs as expected on the master but not devel branch of this repository - one difference I infer is that on the base r-verse image has migrated from debian:buster on to debian:stretch - I am not sure how these map on to the Ubuntu releases in the link you provided. 

Also this build failure is upstream from the changes that I made and the previous build apparently passed - so it isn't even clear why that would happen. (??)

**Comment by eddelbuettel** [comment]
If you look at the build failure log from the very link you gave you will see _ubuntu_ not debian use---because r-ver is now based on Ubuntu 20.04 aka "focal".  

And yes, Ubuntu sometimes does let software disappear but the simple package search revealed a version in the previous release (19.10) which will likely work.  Anyway, your beef, not mine -- I just wanted to quickly help with the search.  I know nothing about the particular software stack so I leave you to that.

**Comment by cboettig** [comment]
it is already in 4.x images, `latest`, and `devel`, as is `lwgeom`.  We should remove the devel branch here, as devel is now built off the same recipe as used in 4.x scripts, see the README note in this repo and comments in #34

**Pull request closed without merging**
